#ifndef FOLLOWER_MON_SPRITES_H
#define FOLLOWER_MON_SPRITES_H

#include "global.h"
#include "constants/event_objects.h"

#define EVENT_OBJ_PAL_TAG_NONE 0x1102
#define gEventObjectBaseOam_16x16 ((const struct OamData*) 0x83A36F8)
#define gEventObjectBaseOam_16x32 ((const struct OamData*) 0x83A3710)
#define gEventObjectBaseOam_32x32 ((const struct OamData*) 0x83A3718)
#define gEventObjectBaseOam_64x64 ((const struct OamData*) 0x83A3720)
#define gEventObjectSpriteOamTables_16x16 ((const struct SubspriteTable*) 0x83A3748)
#define gEventObjectSpriteOamTables_16x32 ((const struct SubspriteTable*) 0x83A379C)
#define gEventObjectSpriteOamTables_32x32 ((const struct SubspriteTable*) 0x83A37F0)
#define gEventObjectSpriteOamTables_64x64 ((const struct SubspriteTable*) 0x83A38D0)
#define gEventObjectImageAnimTable_PlayerNormal ((const union AnimCmd* const*) 0x83A3470)
#define gEventObjectImageAnimTable_Standard ((const union AnimCmd* const*) 0x83A3368)
#define gEventObjectImageAnimTable_Surfing ((const union AnimCmd* const*) 0x83A3584)
#define gEventObjectImageAnimTable_FieldMove ((const union AnimCmd* const*) 0x83A3638)
#define gEventObjectImageAnimTable_Fishing ((const union AnimCmd* const*) 0x83A3668)
#define gEventObjectImageAnimTable_VsSeekerBike ((const union AnimCmd* const*) 0x83A3640)

#define ANIM_STD_FACE_SOUTH       0
#define ANIM_STD_FACE_NORTH       1
#define ANIM_STD_FACE_WEST        2
#define ANIM_STD_FACE_EAST        3
#define ANIM_STD_GO_SOUTH         4
#define ANIM_STD_GO_NORTH         5
#define ANIM_STD_GO_WEST          6
#define ANIM_STD_GO_EAST          7
#define ANIM_STD_GO_FAST_SOUTH    8
#define ANIM_STD_GO_FAST_NORTH    9
#define ANIM_STD_GO_FAST_WEST     10
#define ANIM_STD_GO_FAST_EAST     11
#define ANIM_STD_GO_FASTER_SOUTH  12
#define ANIM_STD_GO_FASTER_NORTH  13
#define ANIM_STD_GO_FASTER_WEST   14
#define ANIM_STD_GO_FASTER_EAST   15
#define ANIM_STD_GO_FASTEST_SOUTH 16
#define ANIM_STD_GO_FASTEST_NORTH 17
#define ANIM_STD_GO_FASTEST_WEST  18
#define ANIM_STD_GO_FASTEST_EAST  19
#define ANIM_RAISE_HAND           20

#define MON_OW_TEMPLATE_32x32_FRAMES(Id, name)                        \
static const struct SpriteFrameImage sMonPicTable_##name[] =          \
{                                                                     \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 0),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 1),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 2),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 3),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 4),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 5),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 6),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 7),    \
    overworld_frame(gFollowerMonPic##Id##_##name##Tiles, 4, 4, 8),    \
};

#define MON_OW_OBJECT_GRAPHICS(PalId, name)                 \
{                                                           \
    .tileTag = 0xFFFF,                                      \
    .paletteTag1 = 0x##PalId,                               \
    .paletteTag2 = EVENT_OBJ_PAL_TAG_NONE,                  \
    .size = (32 * 32) / 2,                                  \
    .width = 32,                                            \
    .height = 32,                                           \
    .shadowSize = SHADOW_SIZE_M,                            \
    .inanimate = FALSE,                                     \
    .disableReflectionPaletteLoad = FALSE,                  \
    .tracks = TRACKS_FOOT,                                  \
    .gender = MALE,                                         \
    .oam = gEventObjectBaseOam_32x32,                       \
    .subspriteTables = gEventObjectSpriteOamTables_32x32,   \
    .anims = gFollowerMonAnimTable,                         \
    .images = sMonPicTable_##name,                          \
    .affineAnims = gDummySpriteAffineAnimTable,             \
},

#define MON_OW_TEMPLATE_64x64_FRAMES(id, name)                          \
static const struct SpriteFrameImage sMonPicTable_##name[] = {             \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 0),    \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 1),    \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 2),    \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 3),    \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 4),    \
    overworld_frame(gFollowerMonPic##id##_##name##Tiles, 8, 8, 5),    \
};

#define MON_OW_OBJECT_GRAPHICS_64(PalId, name)                          \
{                                                                       \
        .tileTag = 0xFFFF,                                              \
        .paletteTag1 = 0x##PalId,                                           \
        .paletteTag2 = EVENT_OBJ_PAL_TAG_NONE,                          \
        .size = (64 * 64) / 2,                                          \
        .width = 64,                                                    \
        .height = 64,                                                   \
        .shadowSize = SHADOW_SIZE_M,                                    \
        .inanimate = FALSE,                                             \
        .disableReflectionPaletteLoad = FALSE,                          \
        .tracks = TRACKS_FOOT,                                          \
        .gender = MALE,                                                 \
        .oam = gEventObjectBaseOam_64x64,                               \
        .subspriteTables = gEventObjectSpriteOamTables_64x64,           \
        .anims = gFollowerMonAnimTable,                                \
        .images = sMonPicTable_##name,                                     \
        .affineAnims = gDummySpriteAffineAnimTable,                     \
},

extern const u16 gFollowerMonSpriteIdTable[];
extern const u16 gFollowerMonShinySpriteIdTable[];
extern const union AnimCmd *const gFollowerMonAnimTable[];

// Overworld Tables
extern const struct EventObjectGraphicsInfo gFollowerMonGfxTable0[];
extern const struct EventObjectGraphicsInfo gFollowerMonGfxTable1[];

// Images declarations
//Gen 1
extern const u8 gFollowerMonPic0001_BulbasaurTiles[];
extern const u8 gFollowerMonPic0002_IvysaurTiles[];
extern const u8 gFollowerMonPic0003_VenusaurTiles[];
extern const u8 gFollowerMonPic0004_CharmanderTiles[];
extern const u8 gFollowerMonPic0005_CharmeleonTiles[];
extern const u8 gFollowerMonPic0006_CharizardTiles[];
extern const u8 gFollowerMonPic0007_SquirtleTiles[];
extern const u8 gFollowerMonPic0008_WartortleTiles[];
extern const u8 gFollowerMonPic0009_BlastoiseTiles[];
extern const u8 gFollowerMonPic0010_CaterpieTiles[];
extern const u8 gFollowerMonPic0011_MetapodTiles[];
extern const u8 gFollowerMonPic0012_ButterfreeTiles[];
extern const u8 gFollowerMonPic0013_WeedleTiles[];
extern const u8 gFollowerMonPic0014_KakunaTiles[];
extern const u8 gFollowerMonPic0015_BeedrillTiles[];
extern const u8 gFollowerMonPic0016_PidgeyTiles[];
extern const u8 gFollowerMonPic0017_PidgeottoTiles[];
extern const u8 gFollowerMonPic0018_PidgeotTiles[];
extern const u8 gFollowerMonPic0019_RattataTiles[];
extern const u8 gFollowerMonPic0020_RaticateTiles[];
extern const u8 gFollowerMonPic0021_SpearowTiles[];
extern const u8 gFollowerMonPic0022_FearowTiles[];
extern const u8 gFollowerMonPic0023_EkansTiles[];
extern const u8 gFollowerMonPic0024_ArbokTiles[];
extern const u8 gFollowerMonPic0025_PikachuTiles[];
extern const u8 gFollowerMonPic0026_RaichuTiles[];
extern const u8 gFollowerMonPic0027_SandshrewTiles[];
extern const u8 gFollowerMonPic0028_SandslashTiles[];
extern const u8 gFollowerMonPic0029_NidoranFTiles[];
extern const u8 gFollowerMonPic0030_NidorinaTiles[];
extern const u8 gFollowerMonPic0031_NidoqueenTiles[];
extern const u8 gFollowerMonPic0032_NidoranMTiles[];
extern const u8 gFollowerMonPic0033_NidorinoTiles[];
extern const u8 gFollowerMonPic0034_NidokingTiles[];
extern const u8 gFollowerMonPic0035_ClefairyTiles[];
extern const u8 gFollowerMonPic0036_ClefableTiles[];
extern const u8 gFollowerMonPic0037_VulpixTiles[];
extern const u8 gFollowerMonPic0038_NinetalesTiles[];
extern const u8 gFollowerMonPic0039_JigglypuffTiles[];
extern const u8 gFollowerMonPic0040_WigglytuffTiles[];
extern const u8 gFollowerMonPic0041_ZubatTiles[];
extern const u8 gFollowerMonPic0042_GolbatTiles[];
extern const u8 gFollowerMonPic0043_OddishTiles[];
extern const u8 gFollowerMonPic0044_GloomTiles[];
extern const u8 gFollowerMonPic0045_VileplumeTiles[];
extern const u8 gFollowerMonPic0046_ParasTiles[];
extern const u8 gFollowerMonPic0047_ParasectTiles[];
extern const u8 gFollowerMonPic0048_VenonatTiles[];
extern const u8 gFollowerMonPic0049_VenomothTiles[];
extern const u8 gFollowerMonPic0050_DiglettTiles[];
extern const u8 gFollowerMonPic0051_DugtrioTiles[];
extern const u8 gFollowerMonPic0052_MeowthTiles[];
extern const u8 gFollowerMonPic0053_PersianTiles[];
extern const u8 gFollowerMonPic0054_PsyduckTiles[];
extern const u8 gFollowerMonPic0055_GolduckTiles[];
extern const u8 gFollowerMonPic0056_MankeyTiles[];
extern const u8 gFollowerMonPic0057_PrimeapeTiles[];
extern const u8 gFollowerMonPic0058_GrowlitheTiles[];
extern const u8 gFollowerMonPic0059_ArcanineTiles[];
extern const u8 gFollowerMonPic0060_PoliwagTiles[];
extern const u8 gFollowerMonPic0061_PoliwhirlTiles[];
extern const u8 gFollowerMonPic0062_PoliwrathTiles[];
extern const u8 gFollowerMonPic0063_AbraTiles[];
extern const u8 gFollowerMonPic0064_KadabraTiles[];
extern const u8 gFollowerMonPic0065_AlakazamTiles[];
extern const u8 gFollowerMonPic0066_MachopTiles[];
extern const u8 gFollowerMonPic0067_MachokeTiles[];
extern const u8 gFollowerMonPic0068_MachampTiles[];
extern const u8 gFollowerMonPic0069_BellsproutTiles[];
extern const u8 gFollowerMonPic0070_WeepinbellTiles[];
extern const u8 gFollowerMonPic0071_VictreebelTiles[];
extern const u8 gFollowerMonPic0072_TentacoolTiles[];
extern const u8 gFollowerMonPic0073_TentacruelTiles[];
extern const u8 gFollowerMonPic0074_GeodudeTiles[];
extern const u8 gFollowerMonPic0075_GravelerTiles[];
extern const u8 gFollowerMonPic0076_GolemTiles[];
extern const u8 gFollowerMonPic0077_PonytaTiles[];
extern const u8 gFollowerMonPic0078_RapidashTiles[];
extern const u8 gFollowerMonPic0079_SlowpokeTiles[];
extern const u8 gFollowerMonPic0080_SlowbroTiles[];
extern const u8 gFollowerMonPic0081_MagnemiteTiles[];
extern const u8 gFollowerMonPic0082_MagnetonTiles[];
extern const u8 gFollowerMonPic0083_FarfetchdTiles[];
extern const u8 gFollowerMonPic0084_DoduoTiles[];
extern const u8 gFollowerMonPic0085_DodrioTiles[];
extern const u8 gFollowerMonPic0086_SeelTiles[];
extern const u8 gFollowerMonPic0087_DewgongTiles[];
extern const u8 gFollowerMonPic0088_GrimerTiles[];
extern const u8 gFollowerMonPic0089_MukTiles[];
extern const u8 gFollowerMonPic0090_ShellderTiles[];
extern const u8 gFollowerMonPic0091_CloysterTiles[];
extern const u8 gFollowerMonPic0092_GastlyTiles[];
extern const u8 gFollowerMonPic0093_HaunterTiles[];
extern const u8 gFollowerMonPic0094_GengarTiles[];
extern const u8 gFollowerMonPic0095_OnixTiles[];
extern const u8 gFollowerMonPic0096_DrowzeeTiles[];
extern const u8 gFollowerMonPic0097_HypnoTiles[];
extern const u8 gFollowerMonPic0098_KrabbyTiles[];
extern const u8 gFollowerMonPic0099_KinglerTiles[];
extern const u8 gFollowerMonPic0100_VoltorbTiles[];
extern const u8 gFollowerMonPic0101_ElectrodeTiles[];
extern const u8 gFollowerMonPic0102_ExeggcuteTiles[];
extern const u8 gFollowerMonPic0103_ExeggutorTiles[];
extern const u8 gFollowerMonPic0104_CuboneTiles[];
extern const u8 gFollowerMonPic0105_MarowakTiles[];
extern const u8 gFollowerMonPic0106_HitmonleeTiles[];
extern const u8 gFollowerMonPic0107_HitmonchanTiles[];
extern const u8 gFollowerMonPic0108_LickitungTiles[];
extern const u8 gFollowerMonPic0109_KoffingTiles[];
extern const u8 gFollowerMonPic0110_WeezingTiles[];
extern const u8 gFollowerMonPic0111_RhyhornTiles[];
extern const u8 gFollowerMonPic0112_RhydonTiles[];
extern const u8 gFollowerMonPic0113_ChanseyTiles[];
extern const u8 gFollowerMonPic0114_TangelaTiles[];
extern const u8 gFollowerMonPic0115_KangaskhanTiles[];
extern const u8 gFollowerMonPic0116_HorseaTiles[];
extern const u8 gFollowerMonPic0117_SeadraTiles[];
extern const u8 gFollowerMonPic0118_GoldeenTiles[];
extern const u8 gFollowerMonPic0119_SeakingTiles[];
extern const u8 gFollowerMonPic0120_StaryuTiles[];
extern const u8 gFollowerMonPic0121_StarmieTiles[];
extern const u8 gFollowerMonPic0122_MrMimeTiles[];
extern const u8 gFollowerMonPic0123_ScytherTiles[];
extern const u8 gFollowerMonPic0124_JynxTiles[];
extern const u8 gFollowerMonPic0125_ElectabuzzTiles[];
extern const u8 gFollowerMonPic0126_MagmarTiles[];
extern const u8 gFollowerMonPic0127_PinsirTiles[];
extern const u8 gFollowerMonPic0128_TaurosTiles[];
extern const u8 gFollowerMonPic0129_MagikarpTiles[];
extern const u8 gFollowerMonPic0130_GyaradosTiles[];
extern const u8 gFollowerMonPic0131_LaprasTiles[];
extern const u8 gFollowerMonPic0132_DittoTiles[];
extern const u8 gFollowerMonPic0133_EeveeTiles[];
extern const u8 gFollowerMonPic0134_VaporeonTiles[];
extern const u8 gFollowerMonPic0135_JolteonTiles[];
extern const u8 gFollowerMonPic0136_FlareonTiles[];
extern const u8 gFollowerMonPic0137_PorygonTiles[];
extern const u8 gFollowerMonPic0138_OmanyteTiles[];
extern const u8 gFollowerMonPic0139_OmastarTiles[];
extern const u8 gFollowerMonPic0140_KabutoTiles[];
extern const u8 gFollowerMonPic0141_KabutopsTiles[];
extern const u8 gFollowerMonPic0142_AerodactylTiles[];
extern const u8 gFollowerMonPic0143_SnorlaxTiles[];
extern const u8 gFollowerMonPic0144_ArticunoTiles[];
extern const u8 gFollowerMonPic0145_ZapdosTiles[];
extern const u8 gFollowerMonPic0146_MoltresTiles[];
extern const u8 gFollowerMonPic0147_DratiniTiles[];
extern const u8 gFollowerMonPic0148_DragonairTiles[];
extern const u8 gFollowerMonPic0149_DragoniteTiles[];
extern const u8 gFollowerMonPic0150_MewtwoTiles[];
extern const u8 gFollowerMonPic0151_MewTiles[];
//Gen 2
extern const u8 gFollowerMonPic0152_ChikoritaTiles[];
extern const u8 gFollowerMonPic0153_BayleefTiles[];
extern const u8 gFollowerMonPic0154_MeganiumTiles[];
extern const u8 gFollowerMonPic0155_CyndaquilTiles[];
extern const u8 gFollowerMonPic0156_QuilavaTiles[];
extern const u8 gFollowerMonPic0157_TyphlosionTiles[];
extern const u8 gFollowerMonPic0158_TotodileTiles[];
extern const u8 gFollowerMonPic0159_CroconawTiles[];
extern const u8 gFollowerMonPic0160_FeraligatrTiles[];
extern const u8 gFollowerMonPic0161_SentretTiles[];
extern const u8 gFollowerMonPic0162_FurretTiles[];
extern const u8 gFollowerMonPic0163_HoothootTiles[];
extern const u8 gFollowerMonPic0164_NoctowlTiles[];
extern const u8 gFollowerMonPic0165_LedybaTiles[];
extern const u8 gFollowerMonPic0166_LedianTiles[];
extern const u8 gFollowerMonPic0167_SpinarakTiles[];
extern const u8 gFollowerMonPic0168_AriadosTiles[];
extern const u8 gFollowerMonPic0169_CrobatTiles[];
extern const u8 gFollowerMonPic0170_ChinchouTiles[];
extern const u8 gFollowerMonPic0171_LanturnTiles[];
extern const u8 gFollowerMonPic0172_PichuTiles[];
extern const u8 gFollowerMonPic0173_CleffaTiles[];
extern const u8 gFollowerMonPic0174_IgglybuffTiles[];
extern const u8 gFollowerMonPic0175_TogepiTiles[];
extern const u8 gFollowerMonPic0176_TogeticTiles[];
extern const u8 gFollowerMonPic0177_NatuTiles[];
extern const u8 gFollowerMonPic0178_XatuTiles[];
extern const u8 gFollowerMonPic0179_MareepTiles[];
extern const u8 gFollowerMonPic0180_FlaaffyTiles[];
extern const u8 gFollowerMonPic0181_AmpharosTiles[];
extern const u8 gFollowerMonPic0182_BellossomTiles[];
extern const u8 gFollowerMonPic0183_MarillTiles[];
extern const u8 gFollowerMonPic0184_AzumarillTiles[];
extern const u8 gFollowerMonPic0185_SudowoodoTiles[];
extern const u8 gFollowerMonPic0186_PolitoedTiles[];
extern const u8 gFollowerMonPic0187_HoppipTiles[];
extern const u8 gFollowerMonPic0188_SkiploomTiles[];
extern const u8 gFollowerMonPic0189_JumpluffTiles[];
extern const u8 gFollowerMonPic0190_AipomTiles[];
extern const u8 gFollowerMonPic0191_SunkernTiles[];
extern const u8 gFollowerMonPic0192_SunfloraTiles[];
extern const u8 gFollowerMonPic0193_YanmaTiles[];
extern const u8 gFollowerMonPic0194_WooperTiles[];
extern const u8 gFollowerMonPic0195_QuagsireTiles[];
extern const u8 gFollowerMonPic0196_EspeonTiles[];
extern const u8 gFollowerMonPic0197_UmbreonTiles[];
extern const u8 gFollowerMonPic0198_MurkrowTiles[];
extern const u8 gFollowerMonPic0199_SlowkingTiles[];
extern const u8 gFollowerMonPic0200_MisdreavusTiles[];
extern const u8 gFollowerMonPic0201_UnownTiles[];
extern const u8 gFollowerMonPic0202_WobbuffetTiles[];
extern const u8 gFollowerMonPic0203_GirafarigTiles[];
extern const u8 gFollowerMonPic0204_PinecoTiles[];
extern const u8 gFollowerMonPic0205_ForretressTiles[];
extern const u8 gFollowerMonPic0206_DunsparceTiles[];
extern const u8 gFollowerMonPic0207_GligarTiles[];
extern const u8 gFollowerMonPic0208_SteelixTiles[];
extern const u8 gFollowerMonPic0209_SnubbullTiles[];
extern const u8 gFollowerMonPic0210_GranbullTiles[];
extern const u8 gFollowerMonPic0211_QwilfishTiles[];
extern const u8 gFollowerMonPic0212_ScizorTiles[];
extern const u8 gFollowerMonPic0213_ShuckleTiles[];
extern const u8 gFollowerMonPic0214_HeracrossTiles[];
extern const u8 gFollowerMonPic0215_SneaselTiles[];
extern const u8 gFollowerMonPic0216_TeddiursaTiles[];
extern const u8 gFollowerMonPic0217_UrsaringTiles[];
extern const u8 gFollowerMonPic0218_SlugmaTiles[];
extern const u8 gFollowerMonPic0219_MagcargoTiles[];
extern const u8 gFollowerMonPic0220_SwinubTiles[];
extern const u8 gFollowerMonPic0221_PiloswineTiles[];
extern const u8 gFollowerMonPic0222_CorsolaTiles[];
extern const u8 gFollowerMonPic0223_RemoraidTiles[];
extern const u8 gFollowerMonPic0224_OctilleryTiles[];
extern const u8 gFollowerMonPic0225_DelibirdTiles[];
extern const u8 gFollowerMonPic0226_MantineTiles[];
extern const u8 gFollowerMonPic0227_SkarmoryTiles[];
extern const u8 gFollowerMonPic0228_HoundourTiles[];
extern const u8 gFollowerMonPic0229_HoundoomTiles[];
extern const u8 gFollowerMonPic0230_KingdraTiles[];
extern const u8 gFollowerMonPic0231_PhanpyTiles[];
extern const u8 gFollowerMonPic0232_DonphanTiles[];
extern const u8 gFollowerMonPic0233_Porygon2Tiles[];
extern const u8 gFollowerMonPic0234_StantlerTiles[];
extern const u8 gFollowerMonPic0235_SmeargleTiles[];
extern const u8 gFollowerMonPic0236_TyrogueTiles[];
extern const u8 gFollowerMonPic0237_HitmontopTiles[];
extern const u8 gFollowerMonPic0238_SmoochumTiles[];
extern const u8 gFollowerMonPic0239_ElekidTiles[];
extern const u8 gFollowerMonPic0240_MagbyTiles[];
extern const u8 gFollowerMonPic0241_MiltankTiles[];
extern const u8 gFollowerMonPic0242_BlisseyTiles[];
extern const u8 gFollowerMonPic0243_RaikouTiles[];
extern const u8 gFollowerMonPic0244_EnteiTiles[];
extern const u8 gFollowerMonPic0245_SuicuneTiles[];
extern const u8 gFollowerMonPic0246_LarvitarTiles[];
extern const u8 gFollowerMonPic0247_PupitarTiles[];
extern const u8 gFollowerMonPic0248_TyranitarTiles[];
extern const u8 gFollowerMonPic0249_LugiaTiles[];
extern const u8 gFollowerMonPic0250_HoOhTiles[];
extern const u8 gFollowerMonPic0251_CelebiTiles[];



//Shiny
extern const u8 gFollowerMonPic2001_BulbasaurShinyTiles[];
extern const u8 gFollowerMonPic2002_IvysaurShinyTiles[];
extern const u8 gFollowerMonPic2003_VenusaurShinyTiles[];
extern const u8 gFollowerMonPic2004_CharmanderShinyTiles[];
extern const u8 gFollowerMonPic2005_CharmeleonShinyTiles[];
extern const u8 gFollowerMonPic2006_CharizardShinyTiles[];
extern const u8 gFollowerMonPic2007_SquirtleShinyTiles[];
extern const u8 gFollowerMonPic2008_WartortleShinyTiles[];
extern const u8 gFollowerMonPic2009_BlastoiseShinyTiles[];
extern const u8 gFollowerMonPic2010_CaterpieShinyTiles[];
extern const u8 gFollowerMonPic2011_MetapodShinyTiles[];
extern const u8 gFollowerMonPic2012_ButterfreeShinyTiles[];
extern const u8 gFollowerMonPic2013_WeedleShinyTiles[];
extern const u8 gFollowerMonPic2014_KakunaShinyTiles[];
extern const u8 gFollowerMonPic2015_BeedrillShinyTiles[];
extern const u8 gFollowerMonPic2016_PidgeyShinyTiles[];
extern const u8 gFollowerMonPic2017_PidgeottoShinyTiles[];
extern const u8 gFollowerMonPic2018_PidgeotShinyTiles[];
extern const u8 gFollowerMonPic2019_RattataShinyTiles[];
extern const u8 gFollowerMonPic2020_RaticateShinyTiles[];
extern const u8 gFollowerMonPic2021_SpearowShinyTiles[];
extern const u8 gFollowerMonPic2022_FearowShinyTiles[];
extern const u8 gFollowerMonPic2023_EkansShinyTiles[];
extern const u8 gFollowerMonPic2024_ArbokShinyTiles[];
extern const u8 gFollowerMonPic2025_PikachuShinyTiles[];
extern const u8 gFollowerMonPic2026_RaichuShinyTiles[];
extern const u8 gFollowerMonPic2027_SandshrewShinyTiles[];
extern const u8 gFollowerMonPic2028_SandslashShinyTiles[];
extern const u8 gFollowerMonPic2029_NidoranFShinyTiles[];
extern const u8 gFollowerMonPic2030_NidorinaShinyTiles[];
extern const u8 gFollowerMonPic2031_NidoqueenShinyTiles[];
extern const u8 gFollowerMonPic2032_NidoranMShinyTiles[];
extern const u8 gFollowerMonPic2033_NidorinoShinyTiles[];
extern const u8 gFollowerMonPic2034_NidokingShinyTiles[];
extern const u8 gFollowerMonPic2035_ClefairyShinyTiles[];
extern const u8 gFollowerMonPic2036_ClefableShinyTiles[];
extern const u8 gFollowerMonPic2037_VulpixShinyTiles[];
extern const u8 gFollowerMonPic2038_NinetalesShinyTiles[];
extern const u8 gFollowerMonPic2039_JigglypuffShinyTiles[];
extern const u8 gFollowerMonPic2040_WigglytuffShinyTiles[];
extern const u8 gFollowerMonPic2041_ZubatShinyTiles[];
extern const u8 gFollowerMonPic2042_GolbatShinyTiles[];
extern const u8 gFollowerMonPic2043_OddishShinyTiles[];
extern const u8 gFollowerMonPic2044_GloomShinyTiles[];
extern const u8 gFollowerMonPic2045_VileplumeShinyTiles[];
extern const u8 gFollowerMonPic2046_ParasShinyTiles[];
extern const u8 gFollowerMonPic2047_ParasectShinyTiles[];
extern const u8 gFollowerMonPic2048_VenonatShinyTiles[];
extern const u8 gFollowerMonPic2049_VenomothShinyTiles[];
extern const u8 gFollowerMonPic2050_DiglettShinyTiles[];
extern const u8 gFollowerMonPic2051_DugtrioShinyTiles[];
extern const u8 gFollowerMonPic2052_MeowthShinyTiles[];
extern const u8 gFollowerMonPic2053_PersianShinyTiles[];
extern const u8 gFollowerMonPic2054_PsyduckShinyTiles[];
extern const u8 gFollowerMonPic2055_GolduckShinyTiles[];
extern const u8 gFollowerMonPic2056_MankeyShinyTiles[];
extern const u8 gFollowerMonPic2057_PrimeapeShinyTiles[];
extern const u8 gFollowerMonPic2058_GrowlitheShinyTiles[];
extern const u8 gFollowerMonPic2059_ArcanineShinyTiles[];
extern const u8 gFollowerMonPic2060_PoliwagShinyTiles[];
extern const u8 gFollowerMonPic2061_PoliwhirlShinyTiles[];
extern const u8 gFollowerMonPic2062_PoliwrathShinyTiles[];
extern const u8 gFollowerMonPic2063_AbraShinyTiles[];
extern const u8 gFollowerMonPic2064_KadabraShinyTiles[];
extern const u8 gFollowerMonPic2065_AlakazamShinyTiles[];
extern const u8 gFollowerMonPic2066_MachopShinyTiles[];
extern const u8 gFollowerMonPic2067_MachokeShinyTiles[];
extern const u8 gFollowerMonPic2068_MachampShinyTiles[];
extern const u8 gFollowerMonPic2069_BellsproutShinyTiles[];
extern const u8 gFollowerMonPic2070_WeepinbellShinyTiles[];
extern const u8 gFollowerMonPic2071_VictreebelShinyTiles[];
extern const u8 gFollowerMonPic2072_TentacoolShinyTiles[];
extern const u8 gFollowerMonPic2073_TentacruelShinyTiles[];
extern const u8 gFollowerMonPic2074_GeodudeShinyTiles[];
extern const u8 gFollowerMonPic2075_GravelerShinyTiles[];
extern const u8 gFollowerMonPic2076_GolemShinyTiles[];
extern const u8 gFollowerMonPic2077_PonytaShinyTiles[];
extern const u8 gFollowerMonPic2078_RapidashShinyTiles[];
extern const u8 gFollowerMonPic2079_SlowpokeShinyTiles[];
extern const u8 gFollowerMonPic2080_SlowbroShinyTiles[];
extern const u8 gFollowerMonPic2081_MagnemiteShinyTiles[];
extern const u8 gFollowerMonPic2082_MagnetonShinyTiles[];
extern const u8 gFollowerMonPic2083_FarfetchdShinyTiles[];
extern const u8 gFollowerMonPic2084_DoduoShinyTiles[];
extern const u8 gFollowerMonPic2085_DodrioShinyTiles[];
extern const u8 gFollowerMonPic2086_SeelShinyTiles[];
extern const u8 gFollowerMonPic2087_DewgongShinyTiles[];
extern const u8 gFollowerMonPic2088_GrimerShinyTiles[];
extern const u8 gFollowerMonPic2089_MukShinyTiles[];
extern const u8 gFollowerMonPic2090_ShellderShinyTiles[];
extern const u8 gFollowerMonPic2091_CloysterShinyTiles[];
extern const u8 gFollowerMonPic2092_GastlyShinyTiles[];
extern const u8 gFollowerMonPic2093_HaunterShinyTiles[];
extern const u8 gFollowerMonPic2094_GengarShinyTiles[];
extern const u8 gFollowerMonPic2095_OnixShinyTiles[];
extern const u8 gFollowerMonPic2096_DrowzeeShinyTiles[];
extern const u8 gFollowerMonPic2097_HypnoShinyTiles[];
extern const u8 gFollowerMonPic2098_KrabbyShinyTiles[];
extern const u8 gFollowerMonPic2099_KinglerShinyTiles[];
extern const u8 gFollowerMonPic2100_VoltorbShinyTiles[];
extern const u8 gFollowerMonPic2101_ElectrodeShinyTiles[];
extern const u8 gFollowerMonPic2102_ExeggcuteShinyTiles[];
extern const u8 gFollowerMonPic2103_ExeggutorShinyTiles[];
extern const u8 gFollowerMonPic2104_CuboneShinyTiles[];
extern const u8 gFollowerMonPic2105_MarowakShinyTiles[];
extern const u8 gFollowerMonPic2106_HitmonleeShinyTiles[];
extern const u8 gFollowerMonPic2107_HitmonchanShinyTiles[];
extern const u8 gFollowerMonPic2108_LickitungShinyTiles[];
extern const u8 gFollowerMonPic2109_KoffingShinyTiles[];
extern const u8 gFollowerMonPic2110_WeezingShinyTiles[];
extern const u8 gFollowerMonPic2111_RhyhornShinyTiles[];
extern const u8 gFollowerMonPic2112_RhydonShinyTiles[];
extern const u8 gFollowerMonPic2113_ChanseyShinyTiles[];
extern const u8 gFollowerMonPic2114_TangelaShinyTiles[];
extern const u8 gFollowerMonPic2115_KangaskhanShinyTiles[];
extern const u8 gFollowerMonPic2116_HorseaShinyTiles[];
extern const u8 gFollowerMonPic2117_SeadraShinyTiles[];
extern const u8 gFollowerMonPic2118_GoldeenShinyTiles[];
extern const u8 gFollowerMonPic2119_SeakingShinyTiles[];
extern const u8 gFollowerMonPic2120_StaryuShinyTiles[];
extern const u8 gFollowerMonPic2121_StarmieShinyTiles[];
extern const u8 gFollowerMonPic2122_MrMimeShinyTiles[];
extern const u8 gFollowerMonPic2123_ScytherShinyTiles[];
extern const u8 gFollowerMonPic2124_JynxShinyTiles[];
extern const u8 gFollowerMonPic2125_ElectabuzzShinyTiles[];
extern const u8 gFollowerMonPic2126_MagmarShinyTiles[];
extern const u8 gFollowerMonPic2127_PinsirShinyTiles[];
extern const u8 gFollowerMonPic2128_TaurosShinyTiles[];
extern const u8 gFollowerMonPic2129_MagikarpShinyTiles[];
extern const u8 gFollowerMonPic2130_GyaradosShinyTiles[];
extern const u8 gFollowerMonPic2131_LaprasShinyTiles[];
extern const u8 gFollowerMonPic2132_DittoShinyTiles[];
extern const u8 gFollowerMonPic2133_EeveeShinyTiles[];
extern const u8 gFollowerMonPic2134_VaporeonShinyTiles[];
extern const u8 gFollowerMonPic2135_JolteonShinyTiles[];
extern const u8 gFollowerMonPic2136_FlareonShinyTiles[];
extern const u8 gFollowerMonPic2137_PorygonShinyTiles[];
extern const u8 gFollowerMonPic2138_OmanyteShinyTiles[];
extern const u8 gFollowerMonPic2139_OmastarShinyTiles[];
extern const u8 gFollowerMonPic2140_KabutoShinyTiles[];
extern const u8 gFollowerMonPic2141_KabutopsShinyTiles[];
extern const u8 gFollowerMonPic2142_AerodactylShinyTiles[];
extern const u8 gFollowerMonPic2143_SnorlaxShinyTiles[];
extern const u8 gFollowerMonPic2144_ArticunoShinyTiles[];
extern const u8 gFollowerMonPic2145_ZapdosShinyTiles[];
extern const u8 gFollowerMonPic2146_MoltresShinyTiles[];
extern const u8 gFollowerMonPic2147_DratiniShinyTiles[];
extern const u8 gFollowerMonPic2148_DragonairShinyTiles[];
extern const u8 gFollowerMonPic2149_DragoniteShinyTiles[];
extern const u8 gFollowerMonPic2150_MewtwoShinyTiles[];
extern const u8 gFollowerMonPic2151_MewShinyTiles[];
// Gen 2
extern const u8 gFollowerMonPic2152_ChikoritaShinyTiles[];
extern const u8 gFollowerMonPic2153_BayleefShinyTiles[];
extern const u8 gFollowerMonPic2154_MeganiumShinyTiles[];
extern const u8 gFollowerMonPic2155_CyndaquilShinyTiles[];
extern const u8 gFollowerMonPic2156_QuilavaShinyTiles[];
extern const u8 gFollowerMonPic2157_TyphlosionShinyTiles[];
extern const u8 gFollowerMonPic2158_TotodileShinyTiles[];
extern const u8 gFollowerMonPic2159_CroconawShinyTiles[];
extern const u8 gFollowerMonPic2160_FeraligatrShinyTiles[];
extern const u8 gFollowerMonPic2161_SentretShinyTiles[];
extern const u8 gFollowerMonPic2162_FurretShinyTiles[];
extern const u8 gFollowerMonPic2163_HoothootShinyTiles[];
extern const u8 gFollowerMonPic2164_NoctowlShinyTiles[];
extern const u8 gFollowerMonPic2165_LedybaShinyTiles[];
extern const u8 gFollowerMonPic2166_LedianShinyTiles[];
extern const u8 gFollowerMonPic2167_SpinarakShinyTiles[];
extern const u8 gFollowerMonPic2168_AriadosShinyTiles[];
extern const u8 gFollowerMonPic2169_CrobatShinyTiles[];
extern const u8 gFollowerMonPic2170_ChinchouShinyTiles[];
extern const u8 gFollowerMonPic2171_LanturnShinyTiles[];
extern const u8 gFollowerMonPic2172_PichuShinyTiles[];
extern const u8 gFollowerMonPic2173_CleffaShinyTiles[];
extern const u8 gFollowerMonPic2174_IgglybuffShinyTiles[];
extern const u8 gFollowerMonPic2175_TogepiShinyTiles[];
extern const u8 gFollowerMonPic2176_TogeticShinyTiles[];
extern const u8 gFollowerMonPic2177_NatuShinyTiles[];
extern const u8 gFollowerMonPic2178_XatuShinyTiles[];
extern const u8 gFollowerMonPic2179_MareepShinyTiles[];
extern const u8 gFollowerMonPic2180_FlaaffyShinyTiles[];
extern const u8 gFollowerMonPic2181_AmpharosShinyTiles[];
extern const u8 gFollowerMonPic2182_BellossomShinyTiles[];
extern const u8 gFollowerMonPic2183_MarillShinyTiles[];
extern const u8 gFollowerMonPic2184_AzumarillShinyTiles[];
extern const u8 gFollowerMonPic2185_SudowoodoShinyTiles[];
extern const u8 gFollowerMonPic2186_PolitoedShinyTiles[];
extern const u8 gFollowerMonPic2187_HoppipShinyTiles[];
extern const u8 gFollowerMonPic2188_SkiploomShinyTiles[];
extern const u8 gFollowerMonPic2189_JumpluffShinyTiles[];
extern const u8 gFollowerMonPic2190_AipomShinyTiles[];
extern const u8 gFollowerMonPic2191_SunkernShinyTiles[];
extern const u8 gFollowerMonPic2192_SunfloraShinyTiles[];
extern const u8 gFollowerMonPic2193_YanmaShinyTiles[];
extern const u8 gFollowerMonPic2194_WooperShinyTiles[];
extern const u8 gFollowerMonPic2195_QuagsireShinyTiles[];
extern const u8 gFollowerMonPic2196_EspeonShinyTiles[];
extern const u8 gFollowerMonPic2197_UmbreonShinyTiles[];
extern const u8 gFollowerMonPic2198_MurkrowShinyTiles[];
extern const u8 gFollowerMonPic2199_SlowkingShinyTiles[];
extern const u8 gFollowerMonPic2200_MisdreavusShinyTiles[];
extern const u8 gFollowerMonPic2201_UnownShinyTiles[];
extern const u8 gFollowerMonPic2202_WobbuffetShinyTiles[];
extern const u8 gFollowerMonPic2203_GirafarigShinyTiles[];
extern const u8 gFollowerMonPic2204_PinecoShinyTiles[];
extern const u8 gFollowerMonPic2205_ForretressShinyTiles[];
extern const u8 gFollowerMonPic2206_DunsparceShinyTiles[];
extern const u8 gFollowerMonPic2207_GligarShinyTiles[];
extern const u8 gFollowerMonPic2208_SteelixShinyTiles[];
extern const u8 gFollowerMonPic2209_SnubbullShinyTiles[];
extern const u8 gFollowerMonPic2210_GranbullShinyTiles[];
extern const u8 gFollowerMonPic2211_QwilfishShinyTiles[];
extern const u8 gFollowerMonPic2212_ScizorShinyTiles[];
extern const u8 gFollowerMonPic2213_ShuckleShinyTiles[];
extern const u8 gFollowerMonPic2214_HeracrossShinyTiles[];
extern const u8 gFollowerMonPic2215_SneaselShinyTiles[];
extern const u8 gFollowerMonPic2216_TeddiursaShinyTiles[];
extern const u8 gFollowerMonPic2217_UrsaringShinyTiles[];
extern const u8 gFollowerMonPic2218_SlugmaShinyTiles[];
extern const u8 gFollowerMonPic2219_MagcargoShinyTiles[];
extern const u8 gFollowerMonPic2220_SwinubShinyTiles[];
extern const u8 gFollowerMonPic2221_PiloswineShinyTiles[];
extern const u8 gFollowerMonPic2222_CorsolaShinyTiles[];
extern const u8 gFollowerMonPic2223_RemoraidShinyTiles[];
extern const u8 gFollowerMonPic2224_OctilleryShinyTiles[];
extern const u8 gFollowerMonPic2225_DelibirdShinyTiles[];
extern const u8 gFollowerMonPic2226_MantineShinyTiles[];
extern const u8 gFollowerMonPic2227_SkarmoryShinyTiles[];
extern const u8 gFollowerMonPic2228_HoundourShinyTiles[];
extern const u8 gFollowerMonPic2229_HoundoomShinyTiles[];
extern const u8 gFollowerMonPic2230_KingdraShinyTiles[];
extern const u8 gFollowerMonPic2231_PhanpyShinyTiles[];
extern const u8 gFollowerMonPic2232_DonphanShinyTiles[];
extern const u8 gFollowerMonPic2233_Porygon2ShinyTiles[];
extern const u8 gFollowerMonPic2234_StantlerShinyTiles[];
extern const u8 gFollowerMonPic2235_SmeargleShinyTiles[];
extern const u8 gFollowerMonPic2236_TyrogueShinyTiles[];
extern const u8 gFollowerMonPic2237_HitmontopShinyTiles[];
extern const u8 gFollowerMonPic2238_SmoochumShinyTiles[];
extern const u8 gFollowerMonPic2239_ElekidShinyTiles[];
extern const u8 gFollowerMonPic2240_MagbyShinyTiles[];
extern const u8 gFollowerMonPic2241_MiltankShinyTiles[];
extern const u8 gFollowerMonPic2242_BlisseyShinyTiles[];
extern const u8 gFollowerMonPic2243_RaikouShinyTiles[];
extern const u8 gFollowerMonPic2244_EnteiShinyTiles[];
extern const u8 gFollowerMonPic2245_SuicuneShinyTiles[];
extern const u8 gFollowerMonPic2246_LarvitarShinyTiles[];
extern const u8 gFollowerMonPic2247_PupitarShinyTiles[];
extern const u8 gFollowerMonPic2248_TyranitarShinyTiles[];
extern const u8 gFollowerMonPic2249_LugiaShinyTiles[];
extern const u8 gFollowerMonPic2250_HoOhShinyTiles[];
extern const u8 gFollowerMonPic2251_CelebiShinyTiles[];



// Palettes declarations
// Gen 1
extern const u16 gFollowerMonPic0001_BulbasaurPal[];
extern const u16 gFollowerMonPic0002_IvysaurPal[];
extern const u16 gFollowerMonPic0003_VenusaurPal[];
extern const u16 gFollowerMonPic0004_CharmanderPal[];
extern const u16 gFollowerMonPic0005_CharmeleonPal[];
extern const u16 gFollowerMonPic0006_CharizardPal[];
extern const u16 gFollowerMonPic0007_SquirtlePal[];
extern const u16 gFollowerMonPic0008_WartortlePal[];
extern const u16 gFollowerMonPic0009_BlastoisePal[];
extern const u16 gFollowerMonPic0010_CaterpiePal[];
extern const u16 gFollowerMonPic0011_MetapodPal[];
extern const u16 gFollowerMonPic0012_ButterfreePal[];
extern const u16 gFollowerMonPic0013_WeedlePal[];
extern const u16 gFollowerMonPic0014_KakunaPal[];
extern const u16 gFollowerMonPic0015_BeedrillPal[];
extern const u16 gFollowerMonPic0016_PidgeyPal[];
extern const u16 gFollowerMonPic0017_PidgeottoPal[];
extern const u16 gFollowerMonPic0018_PidgeotPal[];
extern const u16 gFollowerMonPic0019_RattataPal[];
extern const u16 gFollowerMonPic0020_RaticatePal[];
extern const u16 gFollowerMonPic0021_SpearowPal[];
extern const u16 gFollowerMonPic0022_FearowPal[];
extern const u16 gFollowerMonPic0023_EkansPal[];
extern const u16 gFollowerMonPic0024_ArbokPal[];
extern const u16 gFollowerMonPic0025_PikachuPal[];
extern const u16 gFollowerMonPic0026_RaichuPal[];
extern const u16 gFollowerMonPic0027_SandshrewPal[];
extern const u16 gFollowerMonPic0028_SandslashPal[];
extern const u16 gFollowerMonPic0029_NidoranFPal[];
extern const u16 gFollowerMonPic0030_NidorinaPal[];
extern const u16 gFollowerMonPic0031_NidoqueenPal[];
extern const u16 gFollowerMonPic0032_NidoranMPal[];
extern const u16 gFollowerMonPic0033_NidorinoPal[];
extern const u16 gFollowerMonPic0034_NidokingPal[];
extern const u16 gFollowerMonPic0035_ClefairyPal[];
extern const u16 gFollowerMonPic0036_ClefablePal[];
extern const u16 gFollowerMonPic0037_VulpixPal[];
extern const u16 gFollowerMonPic0038_NinetalesPal[];
extern const u16 gFollowerMonPic0039_JigglypuffPal[];
extern const u16 gFollowerMonPic0040_WigglytuffPal[];
extern const u16 gFollowerMonPic0041_ZubatPal[];
extern const u16 gFollowerMonPic0042_GolbatPal[];
extern const u16 gFollowerMonPic0043_OddishPal[];
extern const u16 gFollowerMonPic0044_GloomPal[];
extern const u16 gFollowerMonPic0045_VileplumePal[];
extern const u16 gFollowerMonPic0046_ParasPal[];
extern const u16 gFollowerMonPic0047_ParasectPal[];
extern const u16 gFollowerMonPic0048_VenonatPal[];
extern const u16 gFollowerMonPic0049_VenomothPal[];
extern const u16 gFollowerMonPic0050_DiglettPal[];
extern const u16 gFollowerMonPic0051_DugtrioPal[];
extern const u16 gFollowerMonPic0052_MeowthPal[];
extern const u16 gFollowerMonPic0053_PersianPal[];
extern const u16 gFollowerMonPic0054_PsyduckPal[];
extern const u16 gFollowerMonPic0055_GolduckPal[];
extern const u16 gFollowerMonPic0056_MankeyPal[];
extern const u16 gFollowerMonPic0057_PrimeapePal[];
extern const u16 gFollowerMonPic0058_GrowlithePal[];
extern const u16 gFollowerMonPic0059_ArcaninePal[];
extern const u16 gFollowerMonPic0060_PoliwagPal[];
extern const u16 gFollowerMonPic0061_PoliwhirlPal[];
extern const u16 gFollowerMonPic0062_PoliwrathPal[];
extern const u16 gFollowerMonPic0063_AbraPal[];
extern const u16 gFollowerMonPic0064_KadabraPal[];
extern const u16 gFollowerMonPic0065_AlakazamPal[];
extern const u16 gFollowerMonPic0066_MachopPal[];
extern const u16 gFollowerMonPic0067_MachokePal[];
extern const u16 gFollowerMonPic0068_MachampPal[];
extern const u16 gFollowerMonPic0069_BellsproutPal[];
extern const u16 gFollowerMonPic0070_WeepinbellPal[];
extern const u16 gFollowerMonPic0071_VictreebelPal[];
extern const u16 gFollowerMonPic0072_TentacoolPal[];
extern const u16 gFollowerMonPic0073_TentacruelPal[];
extern const u16 gFollowerMonPic0074_GeodudePal[];
extern const u16 gFollowerMonPic0075_GravelerPal[];
extern const u16 gFollowerMonPic0076_GolemPal[];
extern const u16 gFollowerMonPic0077_PonytaPal[];
extern const u16 gFollowerMonPic0078_RapidashPal[];
extern const u16 gFollowerMonPic0079_SlowpokePal[];
extern const u16 gFollowerMonPic0080_SlowbroPal[];
extern const u16 gFollowerMonPic0081_MagnemitePal[];
extern const u16 gFollowerMonPic0082_MagnetonPal[];
extern const u16 gFollowerMonPic0083_FarfetchdPal[];
extern const u16 gFollowerMonPic0084_DoduoPal[];
extern const u16 gFollowerMonPic0085_DodrioPal[];
extern const u16 gFollowerMonPic0086_SeelPal[];
extern const u16 gFollowerMonPic0087_DewgongPal[];
extern const u16 gFollowerMonPic0088_GrimerPal[];
extern const u16 gFollowerMonPic0089_MukPal[];
extern const u16 gFollowerMonPic0090_ShellderPal[];
extern const u16 gFollowerMonPic0091_CloysterPal[];
extern const u16 gFollowerMonPic0092_GastlyPal[];
extern const u16 gFollowerMonPic0093_HaunterPal[];
extern const u16 gFollowerMonPic0094_GengarPal[];
extern const u16 gFollowerMonPic0095_OnixPal[];
extern const u16 gFollowerMonPic0096_DrowzeePal[];
extern const u16 gFollowerMonPic0097_HypnoPal[];
extern const u16 gFollowerMonPic0098_KrabbyPal[];
extern const u16 gFollowerMonPic0099_KinglerPal[];
extern const u16 gFollowerMonPic0100_VoltorbPal[];
extern const u16 gFollowerMonPic0101_ElectrodePal[];
extern const u16 gFollowerMonPic0102_ExeggcutePal[];
extern const u16 gFollowerMonPic0103_ExeggutorPal[];
extern const u16 gFollowerMonPic0104_CubonePal[];
extern const u16 gFollowerMonPic0105_MarowakPal[];
extern const u16 gFollowerMonPic0106_HitmonleePal[];
extern const u16 gFollowerMonPic0107_HitmonchanPal[];
extern const u16 gFollowerMonPic0108_LickitungPal[];
extern const u16 gFollowerMonPic0109_KoffingPal[];
extern const u16 gFollowerMonPic0110_WeezingPal[];
extern const u16 gFollowerMonPic0111_RhyhornPal[];
extern const u16 gFollowerMonPic0112_RhydonPal[];
extern const u16 gFollowerMonPic0113_ChanseyPal[];
extern const u16 gFollowerMonPic0114_TangelaPal[];
extern const u16 gFollowerMonPic0115_KangaskhanPal[];
extern const u16 gFollowerMonPic0116_HorseaPal[];
extern const u16 gFollowerMonPic0117_SeadraPal[];
extern const u16 gFollowerMonPic0118_GoldeenPal[];
extern const u16 gFollowerMonPic0119_SeakingPal[];
extern const u16 gFollowerMonPic0120_StaryuPal[];
extern const u16 gFollowerMonPic0121_StarmiePal[];
extern const u16 gFollowerMonPic0122_MrMimePal[];
extern const u16 gFollowerMonPic0123_ScytherPal[];
extern const u16 gFollowerMonPic0124_JynxPal[];
extern const u16 gFollowerMonPic0125_ElectabuzzPal[];
extern const u16 gFollowerMonPic0126_MagmarPal[];
extern const u16 gFollowerMonPic0127_PinsirPal[];
extern const u16 gFollowerMonPic0128_TaurosPal[];
extern const u16 gFollowerMonPic0129_MagikarpPal[];
extern const u16 gFollowerMonPic0130_GyaradosPal[];
extern const u16 gFollowerMonPic0131_LaprasPal[];
extern const u16 gFollowerMonPic0132_DittoPal[];
extern const u16 gFollowerMonPic0133_EeveePal[];
extern const u16 gFollowerMonPic0134_VaporeonPal[];
extern const u16 gFollowerMonPic0135_JolteonPal[];
extern const u16 gFollowerMonPic0136_FlareonPal[];
extern const u16 gFollowerMonPic0137_PorygonPal[];
extern const u16 gFollowerMonPic0138_OmanytePal[];
extern const u16 gFollowerMonPic0139_OmastarPal[];
extern const u16 gFollowerMonPic0140_KabutoPal[];
extern const u16 gFollowerMonPic0141_KabutopsPal[];
extern const u16 gFollowerMonPic0142_AerodactylPal[];
extern const u16 gFollowerMonPic0143_SnorlaxPal[];
extern const u16 gFollowerMonPic0144_ArticunoPal[];
extern const u16 gFollowerMonPic0145_ZapdosPal[];
extern const u16 gFollowerMonPic0146_MoltresPal[];
extern const u16 gFollowerMonPic0147_DratiniPal[];
extern const u16 gFollowerMonPic0148_DragonairPal[];
extern const u16 gFollowerMonPic0149_DragonitePal[];
extern const u16 gFollowerMonPic0150_MewtwoPal[];
extern const u16 gFollowerMonPic0151_MewPal[];
// Gen 2
extern const u16 gFollowerMonPic0152_ChikoritaPal[];
extern const u16 gFollowerMonPic0153_BayleefPal[];
extern const u16 gFollowerMonPic0154_MeganiumPal[];
extern const u16 gFollowerMonPic0155_CyndaquilPal[];
extern const u16 gFollowerMonPic0156_QuilavaPal[];
extern const u16 gFollowerMonPic0157_TyphlosionPal[];
extern const u16 gFollowerMonPic0158_TotodilePal[];
extern const u16 gFollowerMonPic0159_CroconawPal[];
extern const u16 gFollowerMonPic0160_FeraligatrPal[];
extern const u16 gFollowerMonPic0161_SentretPal[];
extern const u16 gFollowerMonPic0162_FurretPal[];
extern const u16 gFollowerMonPic0163_HoothootPal[];
extern const u16 gFollowerMonPic0164_NoctowlPal[];
extern const u16 gFollowerMonPic0165_LedybaPal[];
extern const u16 gFollowerMonPic0166_LedianPal[];
extern const u16 gFollowerMonPic0167_SpinarakPal[];
extern const u16 gFollowerMonPic0168_AriadosPal[];
extern const u16 gFollowerMonPic0169_CrobatPal[];
extern const u16 gFollowerMonPic0170_ChinchouPal[];
extern const u16 gFollowerMonPic0171_LanturnPal[];
extern const u16 gFollowerMonPic0172_PichuPal[];
extern const u16 gFollowerMonPic0173_CleffaPal[];
extern const u16 gFollowerMonPic0174_IgglybuffPal[];
extern const u16 gFollowerMonPic0175_TogepiPal[];
extern const u16 gFollowerMonPic0176_TogeticPal[];
extern const u16 gFollowerMonPic0177_NatuPal[];
extern const u16 gFollowerMonPic0178_XatuPal[];
extern const u16 gFollowerMonPic0179_MareepPal[];
extern const u16 gFollowerMonPic0180_FlaaffyPal[];
extern const u16 gFollowerMonPic0181_AmpharosPal[];
extern const u16 gFollowerMonPic0182_BellossomPal[];
extern const u16 gFollowerMonPic0183_MarillPal[];
extern const u16 gFollowerMonPic0184_AzumarillPal[];
extern const u16 gFollowerMonPic0185_SudowoodoPal[];
extern const u16 gFollowerMonPic0186_PolitoedPal[];
extern const u16 gFollowerMonPic0187_HoppipPal[];
extern const u16 gFollowerMonPic0188_SkiploomPal[];
extern const u16 gFollowerMonPic0189_JumpluffPal[];
extern const u16 gFollowerMonPic0190_AipomPal[];
extern const u16 gFollowerMonPic0191_SunkernPal[];
extern const u16 gFollowerMonPic0192_SunfloraPal[];
extern const u16 gFollowerMonPic0193_YanmaPal[];
extern const u16 gFollowerMonPic0194_WooperPal[];
extern const u16 gFollowerMonPic0195_QuagsirePal[];
extern const u16 gFollowerMonPic0196_EspeonPal[];
extern const u16 gFollowerMonPic0197_UmbreonPal[];
extern const u16 gFollowerMonPic0198_MurkrowPal[];
extern const u16 gFollowerMonPic0199_SlowkingPal[];
extern const u16 gFollowerMonPic0200_MisdreavusPal[];
extern const u16 gFollowerMonPic0201_UnownPal[];
extern const u16 gFollowerMonPic0202_WobbuffetPal[];
extern const u16 gFollowerMonPic0203_GirafarigPal[];
extern const u16 gFollowerMonPic0204_PinecoPal[];
extern const u16 gFollowerMonPic0205_ForretressPal[];
extern const u16 gFollowerMonPic0206_DunsparcePal[];
extern const u16 gFollowerMonPic0207_GligarPal[];
extern const u16 gFollowerMonPic0208_SteelixPal[];
extern const u16 gFollowerMonPic0209_SnubbullPal[];
extern const u16 gFollowerMonPic0210_GranbullPal[];
extern const u16 gFollowerMonPic0211_QwilfishPal[];
extern const u16 gFollowerMonPic0212_ScizorPal[];
extern const u16 gFollowerMonPic0213_ShucklePal[];
extern const u16 gFollowerMonPic0214_HeracrossPal[];
extern const u16 gFollowerMonPic0215_SneaselPal[];
extern const u16 gFollowerMonPic0216_TeddiursaPal[];
extern const u16 gFollowerMonPic0217_UrsaringPal[];
extern const u16 gFollowerMonPic0218_SlugmaPal[];
extern const u16 gFollowerMonPic0219_MagcargoPal[];
extern const u16 gFollowerMonPic0220_SwinubPal[];
extern const u16 gFollowerMonPic0221_PiloswinePal[];
extern const u16 gFollowerMonPic0222_CorsolaPal[];
extern const u16 gFollowerMonPic0223_RemoraidPal[];
extern const u16 gFollowerMonPic0224_OctilleryPal[];
extern const u16 gFollowerMonPic0225_DelibirdPal[];
extern const u16 gFollowerMonPic0226_MantinePal[];
extern const u16 gFollowerMonPic0227_SkarmoryPal[];
extern const u16 gFollowerMonPic0228_HoundourPal[];
extern const u16 gFollowerMonPic0229_HoundoomPal[];
extern const u16 gFollowerMonPic0230_KingdraPal[];
extern const u16 gFollowerMonPic0231_PhanpyPal[];
extern const u16 gFollowerMonPic0232_DonphanPal[];
extern const u16 gFollowerMonPic0233_Porygon2Pal[];
extern const u16 gFollowerMonPic0234_StantlerPal[];
extern const u16 gFollowerMonPic0235_SmearglePal[];
extern const u16 gFollowerMonPic0236_TyroguePal[];
extern const u16 gFollowerMonPic0237_HitmontopPal[];
extern const u16 gFollowerMonPic0238_SmoochumPal[];
extern const u16 gFollowerMonPic0239_ElekidPal[];
extern const u16 gFollowerMonPic0240_MagbyPal[];
extern const u16 gFollowerMonPic0241_MiltankPal[];
extern const u16 gFollowerMonPic0242_BlisseyPal[];
extern const u16 gFollowerMonPic0243_RaikouPal[];
extern const u16 gFollowerMonPic0244_EnteiPal[];
extern const u16 gFollowerMonPic0245_SuicunePal[];
extern const u16 gFollowerMonPic0246_LarvitarPal[];
extern const u16 gFollowerMonPic0247_PupitarPal[];
extern const u16 gFollowerMonPic0248_TyranitarPal[];
extern const u16 gFollowerMonPic0249_LugiaPal[];
extern const u16 gFollowerMonPic0250_HoOhPal[];
extern const u16 gFollowerMonPic0251_CelebiPal[];


//Shiny
extern const u16 gFollowerMonPic2001_BulbasaurShinyPal[];
extern const u16 gFollowerMonPic2002_IvysaurShinyPal[];
extern const u16 gFollowerMonPic2003_VenusaurShinyPal[];
extern const u16 gFollowerMonPic2004_CharmanderShinyPal[];
extern const u16 gFollowerMonPic2005_CharmeleonShinyPal[];
extern const u16 gFollowerMonPic2006_CharizardShinyPal[];
extern const u16 gFollowerMonPic2007_SquirtleShinyPal[];
extern const u16 gFollowerMonPic2008_WartortleShinyPal[];
extern const u16 gFollowerMonPic2009_BlastoiseShinyPal[];
extern const u16 gFollowerMonPic2010_CaterpieShinyPal[];
extern const u16 gFollowerMonPic2011_MetapodShinyPal[];
extern const u16 gFollowerMonPic2012_ButterfreeShinyPal[];
extern const u16 gFollowerMonPic2013_WeedleShinyPal[];
extern const u16 gFollowerMonPic2014_KakunaShinyPal[];
extern const u16 gFollowerMonPic2015_BeedrillShinyPal[];
extern const u16 gFollowerMonPic2016_PidgeyShinyPal[];
extern const u16 gFollowerMonPic2017_PidgeottoShinyPal[];
extern const u16 gFollowerMonPic2018_PidgeotShinyPal[];
extern const u16 gFollowerMonPic2019_RattataShinyPal[];
extern const u16 gFollowerMonPic2020_RaticateShinyPal[];
extern const u16 gFollowerMonPic2021_SpearowShinyPal[];
extern const u16 gFollowerMonPic2022_FearowShinyPal[];
extern const u16 gFollowerMonPic2023_EkansShinyPal[];
extern const u16 gFollowerMonPic2024_ArbokShinyPal[];
extern const u16 gFollowerMonPic2025_PikachuShinyPal[];
extern const u16 gFollowerMonPic2026_RaichuShinyPal[];
extern const u16 gFollowerMonPic2027_SandshrewShinyPal[];
extern const u16 gFollowerMonPic2028_SandslashShinyPal[];
extern const u16 gFollowerMonPic2029_NidoranFShinyPal[];
extern const u16 gFollowerMonPic2030_NidorinaShinyPal[];
extern const u16 gFollowerMonPic2031_NidoqueenShinyPal[];
extern const u16 gFollowerMonPic2032_NidoranMShinyPal[];
extern const u16 gFollowerMonPic2033_NidorinoShinyPal[];
extern const u16 gFollowerMonPic2034_NidokingShinyPal[];
extern const u16 gFollowerMonPic2035_ClefairyShinyPal[];
extern const u16 gFollowerMonPic2036_ClefableShinyPal[];
extern const u16 gFollowerMonPic2037_VulpixShinyPal[];
extern const u16 gFollowerMonPic2038_NinetalesShinyPal[];
extern const u16 gFollowerMonPic2039_JigglypuffShinyPal[];
extern const u16 gFollowerMonPic2040_WigglytuffShinyPal[];
extern const u16 gFollowerMonPic2041_ZubatShinyPal[];
extern const u16 gFollowerMonPic2042_GolbatShinyPal[];
extern const u16 gFollowerMonPic2043_OddishShinyPal[];
extern const u16 gFollowerMonPic2044_GloomShinyPal[];
extern const u16 gFollowerMonPic2045_VileplumeShinyPal[];
extern const u16 gFollowerMonPic2046_ParasShinyPal[];
extern const u16 gFollowerMonPic2047_ParasectShinyPal[];
extern const u16 gFollowerMonPic2048_VenonatShinyPal[];
extern const u16 gFollowerMonPic2049_VenomothShinyPal[];
extern const u16 gFollowerMonPic2050_DiglettShinyPal[];
extern const u16 gFollowerMonPic2051_DugtrioShinyPal[];
extern const u16 gFollowerMonPic2052_MeowthShinyPal[];
extern const u16 gFollowerMonPic2053_PersianShinyPal[];
extern const u16 gFollowerMonPic2054_PsyduckShinyPal[];
extern const u16 gFollowerMonPic2055_GolduckShinyPal[];
extern const u16 gFollowerMonPic2056_MankeyShinyPal[];
extern const u16 gFollowerMonPic2057_PrimeapeShinyPal[];
extern const u16 gFollowerMonPic2058_GrowlitheShinyPal[];
extern const u16 gFollowerMonPic2059_ArcanineShinyPal[];
extern const u16 gFollowerMonPic2060_PoliwagShinyPal[];
extern const u16 gFollowerMonPic2061_PoliwhirlShinyPal[];
extern const u16 gFollowerMonPic2062_PoliwrathShinyPal[];
extern const u16 gFollowerMonPic2063_AbraShinyPal[];
extern const u16 gFollowerMonPic2064_KadabraShinyPal[];
extern const u16 gFollowerMonPic2065_AlakazamShinyPal[];
extern const u16 gFollowerMonPic2066_MachopShinyPal[];
extern const u16 gFollowerMonPic2067_MachokeShinyPal[];
extern const u16 gFollowerMonPic2068_MachampShinyPal[];
extern const u16 gFollowerMonPic2069_BellsproutShinyPal[];
extern const u16 gFollowerMonPic2070_WeepinbellShinyPal[];
extern const u16 gFollowerMonPic2071_VictreebelShinyPal[];
extern const u16 gFollowerMonPic2072_TentacoolShinyPal[];
extern const u16 gFollowerMonPic2073_TentacruelShinyPal[];
extern const u16 gFollowerMonPic2074_GeodudeShinyPal[];
extern const u16 gFollowerMonPic2075_GravelerShinyPal[];
extern const u16 gFollowerMonPic2076_GolemShinyPal[];
extern const u16 gFollowerMonPic2077_PonytaShinyPal[];
extern const u16 gFollowerMonPic2078_RapidashShinyPal[];
extern const u16 gFollowerMonPic2079_SlowpokeShinyPal[];
extern const u16 gFollowerMonPic2080_SlowbroShinyPal[];
extern const u16 gFollowerMonPic2081_MagnemiteShinyPal[];
extern const u16 gFollowerMonPic2082_MagnetonShinyPal[];
extern const u16 gFollowerMonPic2083_FarfetchdShinyPal[];
extern const u16 gFollowerMonPic2084_DoduoShinyPal[];
extern const u16 gFollowerMonPic2085_DodrioShinyPal[];
extern const u16 gFollowerMonPic2086_SeelShinyPal[];
extern const u16 gFollowerMonPic2087_DewgongShinyPal[];
extern const u16 gFollowerMonPic2088_GrimerShinyPal[];
extern const u16 gFollowerMonPic2089_MukShinyPal[];
extern const u16 gFollowerMonPic2090_ShellderShinyPal[];
extern const u16 gFollowerMonPic2091_CloysterShinyPal[];
extern const u16 gFollowerMonPic2092_GastlyShinyPal[];
extern const u16 gFollowerMonPic2093_HaunterShinyPal[];
extern const u16 gFollowerMonPic2094_GengarShinyPal[];
extern const u16 gFollowerMonPic2095_OnixShinyPal[];
extern const u16 gFollowerMonPic2096_DrowzeeShinyPal[];
extern const u16 gFollowerMonPic2097_HypnoShinyPal[];
extern const u16 gFollowerMonPic2098_KrabbyShinyPal[];
extern const u16 gFollowerMonPic2099_KinglerShinyPal[];
extern const u16 gFollowerMonPic2100_VoltorbShinyPal[];
extern const u16 gFollowerMonPic2101_ElectrodeShinyPal[];
extern const u16 gFollowerMonPic2102_ExeggcuteShinyPal[];
extern const u16 gFollowerMonPic2103_ExeggutorShinyPal[];
extern const u16 gFollowerMonPic2104_CuboneShinyPal[];
extern const u16 gFollowerMonPic2105_MarowakShinyPal[];
extern const u16 gFollowerMonPic2106_HitmonleeShinyPal[];
extern const u16 gFollowerMonPic2107_HitmonchanShinyPal[];
extern const u16 gFollowerMonPic2108_LickitungShinyPal[];
extern const u16 gFollowerMonPic2109_KoffingShinyPal[];
extern const u16 gFollowerMonPic2110_WeezingShinyPal[];
extern const u16 gFollowerMonPic2111_RhyhornShinyPal[];
extern const u16 gFollowerMonPic2112_RhydonShinyPal[];
extern const u16 gFollowerMonPic2113_ChanseyShinyPal[];
extern const u16 gFollowerMonPic2114_TangelaShinyPal[];
extern const u16 gFollowerMonPic2115_KangaskhanShinyPal[];
extern const u16 gFollowerMonPic2116_HorseaShinyPal[];
extern const u16 gFollowerMonPic2117_SeadraShinyPal[];
extern const u16 gFollowerMonPic2118_GoldeenShinyPal[];
extern const u16 gFollowerMonPic2119_SeakingShinyPal[];
extern const u16 gFollowerMonPic2120_StaryuShinyPal[];
extern const u16 gFollowerMonPic2121_StarmieShinyPal[];
extern const u16 gFollowerMonPic2122_MrMimeShinyPal[];
extern const u16 gFollowerMonPic2123_ScytherShinyPal[];
extern const u16 gFollowerMonPic2124_JynxShinyPal[];
extern const u16 gFollowerMonPic2125_ElectabuzzShinyPal[];
extern const u16 gFollowerMonPic2126_MagmarShinyPal[];
extern const u16 gFollowerMonPic2127_PinsirShinyPal[];
extern const u16 gFollowerMonPic2128_TaurosShinyPal[];
extern const u16 gFollowerMonPic2129_MagikarpShinyPal[];
extern const u16 gFollowerMonPic2130_GyaradosShinyPal[];
extern const u16 gFollowerMonPic2131_LaprasShinyPal[];
extern const u16 gFollowerMonPic2132_DittoShinyPal[];
extern const u16 gFollowerMonPic2133_EeveeShinyPal[];
extern const u16 gFollowerMonPic2134_VaporeonShinyPal[];
extern const u16 gFollowerMonPic2135_JolteonShinyPal[];
extern const u16 gFollowerMonPic2136_FlareonShinyPal[];
extern const u16 gFollowerMonPic2137_PorygonShinyPal[];
extern const u16 gFollowerMonPic2138_OmanyteShinyPal[];
extern const u16 gFollowerMonPic2139_OmastarShinyPal[];
extern const u16 gFollowerMonPic2140_KabutoShinyPal[];
extern const u16 gFollowerMonPic2141_KabutopsShinyPal[];
extern const u16 gFollowerMonPic2142_AerodactylShinyPal[];
extern const u16 gFollowerMonPic2143_SnorlaxShinyPal[];
extern const u16 gFollowerMonPic2144_ArticunoShinyPal[];
extern const u16 gFollowerMonPic2145_ZapdosShinyPal[];
extern const u16 gFollowerMonPic2146_MoltresShinyPal[];
extern const u16 gFollowerMonPic2147_DratiniShinyPal[];
extern const u16 gFollowerMonPic2148_DragonairShinyPal[];
extern const u16 gFollowerMonPic2149_DragoniteShinyPal[];
extern const u16 gFollowerMonPic2150_MewtwoShinyPal[];
extern const u16 gFollowerMonPic2151_MewShinyPal[];
// Gen 2
extern const u16 gFollowerMonPic2152_ChikoritaShinyPal[];
extern const u16 gFollowerMonPic2153_BayleefShinyPal[];
extern const u16 gFollowerMonPic2154_MeganiumShinyPal[];
extern const u16 gFollowerMonPic2155_CyndaquilShinyPal[];
extern const u16 gFollowerMonPic2156_QuilavaShinyPal[];
extern const u16 gFollowerMonPic2157_TyphlosionShinyPal[];
extern const u16 gFollowerMonPic2158_TotodileShinyPal[];
extern const u16 gFollowerMonPic2159_CroconawShinyPal[];
extern const u16 gFollowerMonPic2160_FeraligatrShinyPal[];
extern const u16 gFollowerMonPic2161_SentretShinyPal[];
extern const u16 gFollowerMonPic2162_FurretShinyPal[];
extern const u16 gFollowerMonPic2163_HoothootShinyPal[];
extern const u16 gFollowerMonPic2164_NoctowlShinyPal[];
extern const u16 gFollowerMonPic2165_LedybaShinyPal[];
extern const u16 gFollowerMonPic2166_LedianShinyPal[];
extern const u16 gFollowerMonPic2167_SpinarakShinyPal[];
extern const u16 gFollowerMonPic2168_AriadosShinyPal[];
extern const u16 gFollowerMonPic2169_CrobatShinyPal[];
extern const u16 gFollowerMonPic2170_ChinchouShinyPal[];
extern const u16 gFollowerMonPic2171_LanturnShinyPal[];
extern const u16 gFollowerMonPic2172_PichuShinyPal[];
extern const u16 gFollowerMonPic2173_CleffaShinyPal[];
extern const u16 gFollowerMonPic2174_IgglybuffShinyPal[];
extern const u16 gFollowerMonPic2175_TogepiShinyPal[];
extern const u16 gFollowerMonPic2176_TogeticShinyPal[];
extern const u16 gFollowerMonPic2177_NatuShinyPal[];
extern const u16 gFollowerMonPic2178_XatuShinyPal[];
extern const u16 gFollowerMonPic2179_MareepShinyPal[];
extern const u16 gFollowerMonPic2180_FlaaffyShinyPal[];
extern const u16 gFollowerMonPic2181_AmpharosShinyPal[];
extern const u16 gFollowerMonPic2182_BellossomShinyPal[];
extern const u16 gFollowerMonPic2183_MarillShinyPal[];
extern const u16 gFollowerMonPic2184_AzumarillShinyPal[];
extern const u16 gFollowerMonPic2185_SudowoodoShinyPal[];
extern const u16 gFollowerMonPic2186_PolitoedShinyPal[];
extern const u16 gFollowerMonPic2187_HoppipShinyPal[];
extern const u16 gFollowerMonPic2188_SkiploomShinyPal[];
extern const u16 gFollowerMonPic2189_JumpluffShinyPal[];
extern const u16 gFollowerMonPic2190_AipomShinyPal[];
extern const u16 gFollowerMonPic2191_SunkernShinyPal[];
extern const u16 gFollowerMonPic2192_SunfloraShinyPal[];
extern const u16 gFollowerMonPic2193_YanmaShinyPal[];
extern const u16 gFollowerMonPic2194_WooperShinyPal[];
extern const u16 gFollowerMonPic2195_QuagsireShinyPal[];
extern const u16 gFollowerMonPic2196_EspeonShinyPal[];
extern const u16 gFollowerMonPic2197_UmbreonShinyPal[];
extern const u16 gFollowerMonPic2198_MurkrowShinyPal[];
extern const u16 gFollowerMonPic2199_SlowkingShinyPal[];
extern const u16 gFollowerMonPic2200_MisdreavusShinyPal[];
extern const u16 gFollowerMonPic2201_UnownShinyPal[];
extern const u16 gFollowerMonPic2202_WobbuffetShinyPal[];
extern const u16 gFollowerMonPic2203_GirafarigShinyPal[];
extern const u16 gFollowerMonPic2204_PinecoShinyPal[];
extern const u16 gFollowerMonPic2205_ForretressShinyPal[];
extern const u16 gFollowerMonPic2206_DunsparceShinyPal[];
extern const u16 gFollowerMonPic2207_GligarShinyPal[];
extern const u16 gFollowerMonPic2208_SteelixShinyPal[];
extern const u16 gFollowerMonPic2209_SnubbullShinyPal[];
extern const u16 gFollowerMonPic2210_GranbullShinyPal[];
extern const u16 gFollowerMonPic2211_QwilfishShinyPal[];
extern const u16 gFollowerMonPic2212_ScizorShinyPal[];
extern const u16 gFollowerMonPic2213_ShuckleShinyPal[];
extern const u16 gFollowerMonPic2214_HeracrossShinyPal[];
extern const u16 gFollowerMonPic2215_SneaselShinyPal[];
extern const u16 gFollowerMonPic2216_TeddiursaShinyPal[];
extern const u16 gFollowerMonPic2217_UrsaringShinyPal[];
extern const u16 gFollowerMonPic2218_SlugmaShinyPal[];
extern const u16 gFollowerMonPic2219_MagcargoShinyPal[];
extern const u16 gFollowerMonPic2220_SwinubShinyPal[];
extern const u16 gFollowerMonPic2221_PiloswineShinyPal[];
extern const u16 gFollowerMonPic2222_CorsolaShinyPal[];
extern const u16 gFollowerMonPic2223_RemoraidShinyPal[];
extern const u16 gFollowerMonPic2224_OctilleryShinyPal[];
extern const u16 gFollowerMonPic2225_DelibirdShinyPal[];
extern const u16 gFollowerMonPic2226_MantineShinyPal[];
extern const u16 gFollowerMonPic2227_SkarmoryShinyPal[];
extern const u16 gFollowerMonPic2228_HoundourShinyPal[];
extern const u16 gFollowerMonPic2229_HoundoomShinyPal[];
extern const u16 gFollowerMonPic2230_KingdraShinyPal[];
extern const u16 gFollowerMonPic2231_PhanpyShinyPal[];
extern const u16 gFollowerMonPic2232_DonphanShinyPal[];
extern const u16 gFollowerMonPic2233_Porygon2ShinyPal[];
extern const u16 gFollowerMonPic2234_StantlerShinyPal[];
extern const u16 gFollowerMonPic2235_SmeargleShinyPal[];
extern const u16 gFollowerMonPic2236_TyrogueShinyPal[];
extern const u16 gFollowerMonPic2237_HitmontopShinyPal[];
extern const u16 gFollowerMonPic2238_SmoochumShinyPal[];
extern const u16 gFollowerMonPic2239_ElekidShinyPal[];
extern const u16 gFollowerMonPic2240_MagbyShinyPal[];
extern const u16 gFollowerMonPic2241_MiltankShinyPal[];
extern const u16 gFollowerMonPic2242_BlisseyShinyPal[];
extern const u16 gFollowerMonPic2243_RaikouShinyPal[];
extern const u16 gFollowerMonPic2244_EnteiShinyPal[];
extern const u16 gFollowerMonPic2245_SuicuneShinyPal[];
extern const u16 gFollowerMonPic2246_LarvitarShinyPal[];
extern const u16 gFollowerMonPic2247_PupitarShinyPal[];
extern const u16 gFollowerMonPic2248_TyranitarShinyPal[];
extern const u16 gFollowerMonPic2249_LugiaShinyPal[];
extern const u16 gFollowerMonPic2250_HoOhShinyPal[];
extern const u16 gFollowerMonPic2251_CelebiShinyPal[];



#endif